require 'thermite/tasks'
require_relative '../lib/faster_path/version'

project_toplevel_dir = File.dirname(__dir__)
Thermite::Tasks.new(cargo_project_path: project_toplevel_dir,
                    ruby_project_path: project_toplevel_dir,
                    version: FasterPath::VERSION)

task default: 'thermite:build'
