require 'fileutils'
require_relative '../lib/faster_path/build_task'

FasterPath::BuildTask.define

# Keeps the built library (in lib/faster_path, where FasterPath loads it from)
# and removes the rest of Cargo's output from the installed gem.
task install_library: 'rutie:build' do
  FileUtils.mkdir_p(FasterPath::BuildTask::INSTALLED_LIBRARY_DIR)
  FileUtils.cp(FasterPath::BuildTask.built_library, FasterPath::BuildTask::INSTALLED_LIBRARY_DIR)
  Rake::Task['rutie:clean'].invoke
end

task default: :install_library
